### model
model_name_or_path: meta-llama/Llama-3.1-8B-Instruct

### method
stage: dpo
do_train: true
finetuning_type: lora
lora_target: all
pref_beta: 0.1
pref_loss: sigmoid  # choices: [sigmoid (dpo), orpo, simpo]
pref_ftx: 0.1
optim: adamw_torch

### dataset
dataset: llama3_longmab_dpo_data
template: llama3
cutoff_len: 8500
max_samples: 1000000
overwrite_cache: true
preprocessing_num_workers: 16


### output
output_dir: ../checkpoint/llama3_longmab_po_lora
logging_steps: 50
save_steps: 250
plot_loss: true
overwrite_output_dir: true
report_to: tensorboard

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 1
gradient_checkpointing: true
learning_rate: 2.0e-5
num_train_epochs: 2.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
deepspeed: ds_z2_config.json

### eval
val_size: 0.1
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 250
compute_accuracy: true
